[build.environment]
  NODE_VERSION = "20"

[build]
  base = "frontend"
  command = "pnpm install && pnpm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[secrets]
  omit_keys = ["VITE_API_URL", "VITE_GEOAPIFY_API_KEY"]
