[build]
base = "frontend"
command = "chmod +x node_modules/.bin/vite && npm ci && npm run build"
publish = "frontend/dist"


[build.environment]
SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL,VITE_GEOAPIFY_API_KEY"
