convert_dtypes:
  datetime: "datetime64[ns]"

cleaning:
  drop_nulls: true

duration:
  max_seconds: 7200 #drop trips longer than 2 hrs
  drop_zero_durations: true

longitude:
  start_lng_negative_fix: true
  end_lng_fix: true
  end_lng_ocean_threshold: -60

invalid_routes:
  - 90810
  - 81553
  - 83473
  - 87892
  - 96380

saved_paths:
  processed_train: "data/processed/eda_processed_train.csv"
  processed_test: "data/processed/eda_processed_test.csv"
